# Author : Iman Kianian
# 1 January 2021
from gameboard import gameboard
from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_Form(object):
    def setupUi(self, window):   
        window.setObjectName("Form")
        window.resize(597, 420)
        Form = QtWidgets.QWidget(window)
        Form.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.epsilon = QtWidgets.QLineEdit(Form)
        self.epsilon.setObjectName("epsilon")
        self.horizontalLayout_2.addWidget(self.epsilon)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.gamma = QtWidgets.QLineEdit(Form)
        self.gamma.setObjectName("gamma")
        self.horizontalLayout_3.addWidget(self.gamma)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.living = QtWidgets.QLineEdit(Form)
        self.living.setObjectName("living")
        self.horizontalLayout.addWidget(self.living)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.fire = QtWidgets.QLineEdit(Form)
        self.fire.setObjectName("fire")
        self.horizontalLayout_4.addWidget(self.fire)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.diamond = QtWidgets.QLineEdit(Form)
        self.diamond.setObjectName("diamond")
        self.horizontalLayout_5.addWidget(self.diamond)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.Play = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Play.setFont(font)
        self.Play.setObjectName("Play")
        self.verticalLayout.addWidget(self.Play)
        self.Play.clicked.connect(self.gotogame)
        window.setCentralWidget(Form)
        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Grid World Game"))
        self.label.setText(_translate("Form", "Living Reward = "))
        self.label_2.setText(_translate("Form", "ε = "))
        self.label_3.setText(_translate("Form", "γ = "))
        self.label_4.setText(_translate("Form", "Fire Reward = "))
        self.label_5.setText(_translate("Form", "Diamond Reward = "))
        self.Play.setText(_translate("Form", "Play ! "))

    def gotogame(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = gameboard()
        self.ui.setupUi(self.window,float(self.epsilon.text()),float(self.gamma.text()),float(self.living.text()),float(self.fire.text()),float(self.diamond.text()))
        self.window.show()
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

